name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -e .
          python -m pip install black flake8 isort pytest pytest-cov
      - name: Lint with isort
        run: python -m isort -w 80 -m 3 --trailing-comma --check-only .
      - name: Lint with black
        run: python -m black -l 80 .
      - name: Lint with flake8
        run: python -m flake8 --max-line-length=80 .
      - name: Test with pytest
        run: python -m pytest --cov=edolab --cov-fail-under=100 tests
